import { Inter_Tight } from 'next/font/google'
import './globals.css';
import Header from './components/header/Header';

const nunito = Inter_Tight({ subsets: ['latin'] })

export const metadata = {
  title: 'Diego | Personal Portfolio',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={nunito.className}><Header />{children}</body>
    </html>
  )
}
